name: CI Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate HTML structure
      run: |
        echo "Validating basic HTML structure..."
        if [ -f "index.html" ]; then
          echo "✓ index.html exists"
        else
          echo "✗ index.html missing"
          exit 1
        fi

    - name: Check for broken links
      run: |
        echo "Checking for broken links..."
        # Esta es una validación básica, puedes expandirla luego
        echo "✓ Basic link check completed"

    - name: Success message
      run: echo "✅ All validations passed! The site structure looks good."
